import { NEXT_PUBLIC_HELP_PAGE_URL } from '@/config/appConfig';

export const PATH = {
  HOME: '/',
  CARDS: '/cards',
  CARD_DETAILS: '/cards/:id',
  SIGNUP: '/sign-up',
  SIGNIN: '/sign-in',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  EMAIL_VERIFIED: '/email-verified',
  MARKET: '/market',
  MY_TEAM: '/my-team',
  GAME: '/game',
  RULES: '/game/rules',
  REWARDS: '/game/rewards',
  WATCH_TEAMS: '/game/watch-teams',
  GAME_DETAIL: '/game/:gameId',
  INVITE_FRIENDS: '/invite-friends',
  ALL_CARDS: '/all-cards',
  MY_PROFILE: '/my-profile',
  EDIT_PROFILE: '/my-profile/edit',
  VIEW_PROFILE: '/my-profile/view',
  REFERRALS: '/my-profile/referrals',
  REFERRAL_GIFTS: '/my-profile/referral-gifts',
  AFFILIATE_TAKE_REWARD: '/my-profile/affiliate-take-reward/:rewardId',
  AWARDS: '/my-profile/awards',
  MY_BIDS: '/my-profile/my-bids',
  MY_FOLLOWERS: '/my-profile/follows',
  MY_FAVORITES: '/my-profile/favorites',
  MY_SALES: '/my-profile/my-sales',
  HELP: NEXT_PUBLIC_HELP_PAGE_URL,
  TERMS_OF_SERVICE: '/terms-of-service',
  LEGALS_NOTICE: '/legals-notice',
  COOKIES_POLICY: '/cookies-policy',
  PRIVACY_POLICY: '/privacy-policy',
  PARTNERS: '/partners',
  PATICIPATE: '/game/paticipate',
  MAKE_MY_TEAM: '/game/paticipate/:gameId',
  TAKE_REWARD: '/game/take-reward/:gameId',
  WATCH: '/game/watch',
  TEAM_SCORE: '/game/ranking/team-score',
  GAME_TEAMS: '/game/teams',
  BUNDLES: '/bundles',
  USER: '/user',
  USER_DETAIL: '/user/:userId',
  //MY TEAM
  MY_CARDS: '/my-team/my-cards',
  WHITE_CARDS: '/my-team/white-cards',
  AUCTION_WINNINGS: '/my-team/auction-winnings',
  BUNDLE_WINNINGS: '/my-team/bundle-winnings',
  GAME_RANKINGS: '/game/ranking',
  GAME_RANKING_ID: '/game/ranking/:id',
  //COLLECTION
  RIDER_COLLECTIONS: '/rider-collections/:riderId',
  RIDER_SCORE: '/rider-score/:riderId',
  VIEW_NOTIFICATION: '/notifications/:id',
  TAKE_FREE_CARDS: '/take-free-cards',

  TRANSFER_FREE_CARD: '/transfer-free-card',
  SET_DEFAULT_TEAM: '/default-team',
  OPEN_THE_PACK: '/open-the-pack',
};
