import { User } from '@/typings/watch';

export const WATCH_RANKINGS: User[] = [
  {
    id: '1',
    rank: 1,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Marvin McKinney',
    points: 2761,
  },
  {
    id: '2',
    rank: 2,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Leslie Alexander',
    points: 1738,
  },
  {
    id: '3',
    rank: 3,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Floyd Miles',
    points: 1273,
  },
  {
    id: '4',
    rank: 4,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Jerome Bell',
    points: 983,
    highlight: true,
  },
  {
    id: '5',
    rank: 5,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Arlene McCoy',
    points: 827,
  },
  {
    id: '6',
    rank: 6,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Darrell Steward',
    points: 802,
  },
  {
    id: '7',
    rank: 7,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Theresa Webb',
    points: 798,
    highlight: true,
  },
  {
    id: '8',
    rank: 8,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Brooklyn Simmons',
    points: 738,
  },
  {
    id: '9',
    rank: 9,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Jenny Wilson',
    points: 723,
    highlight: true,
  },
  {
    id: '10',
    rank: 10,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Ronald Richards',
    points: 682,
  },
  {
    id: '11',
    rank: 11,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Cameron Williamson',
    points: 619,
  },
  {
    id: '12',
    rank: 12,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Courtney Henry',
    points: 605,
  },
  {
    id: '13',
    rank: 13,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Devon Lane',
    points: 522,
  },
  {
    id: '14',
    rank: 14,
    avatar: 'https://i.pravatar.cc/300',
    name: 'Dianne Russell',
    points: 402,
  },
];
